/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

/**
 *
 * @author marti
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Inicio");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuItem10 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem12RegistrarProductos = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItemRegistrarcliente = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem1stock = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        RegistrarProveedores1 = new javax.swing.JMenuItem();
        jMenuItemconsultaracturaporfecha = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItemRegistrarVendedores = new javax.swing.JMenuItem();
        jMenuItem15facturaaclientesv = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        RegistrarProveedores = new javax.swing.JMenuItem();
        jMenuItem14Proveedoressurten = new javax.swing.JMenuItem();

        jLabel1.setText("jLabel1");

        jMenuItem10.setText("jMenuItem10");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jMenuItem11.setText("jMenuItem11");

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setBackground(new java.awt.Color(153, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/surtido (1).png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setText("SISTEMA DE INVENTARIO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(204, 204, 204));

        jMenu4.setText("Productos");

        jMenuItem8.setText("Entradas");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem8);

        jMenuItem12RegistrarProductos.setText("Registrar");
        jMenuItem12RegistrarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12RegistrarProductosActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem12RegistrarProductos);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Clientes");

        jMenuItemRegistrarcliente.setText("Registrar");
        jMenuItemRegistrarcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegistrarclienteActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItemRegistrarcliente);

        jMenuItem13.setText(" Facturas");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem13);

        jMenuItem19.setText("Saldo pendiente");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem19);

        jMenuBar1.add(jMenu5);

        jMenu8.setText("Inventario");

        jMenuItem1stock.setText("Stock");
        jMenuItem1stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1stockActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem1stock);

        jMenuBar1.add(jMenu8);

        jMenu10.setText("Facturas");

        RegistrarProveedores1.setText("Registrar");
        RegistrarProveedores1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarProveedores1ActionPerformed(evt);
            }
        });
        jMenu10.add(RegistrarProveedores1);

        jMenuItemconsultaracturaporfecha.setText("Fecha de factura");
        jMenuItemconsultaracturaporfecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemconsultaracturaporfechaActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItemconsultaracturaporfecha);

        jMenuItem18.setText("Facturas canceladas");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem18);

        jMenuBar1.add(jMenu10);

        jMenu7.setText("Vendedores");

        jMenuItemRegistrarVendedores.setText("Registrar");
        jMenuItemRegistrarVendedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegistrarVendedoresActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItemRegistrarVendedores);

        jMenuItem15facturaaclientesv.setText("Factura a clientes");
        jMenuItem15facturaaclientesv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15facturaaclientesvActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem15facturaaclientesv);

        jMenuBar1.add(jMenu7);

        jMenu6.setText("Proveedores");

        RegistrarProveedores.setText("Registrar");
        RegistrarProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarProveedoresActionPerformed(evt);
            }
        });
        jMenu6.add(RegistrarProveedores);

        jMenuItem14Proveedoressurten.setText("Proveedores surten Producto");
        jMenuItem14Proveedoressurten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ProveedoressurtenActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem14Proveedoressurten);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        Entradas e = new Entradas();
        e.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItemRegistrarclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegistrarclienteActionPerformed
        RegistrarClientes registrarcliente = new RegistrarClientes();
        registrarcliente.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItemRegistrarclienteActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void RegistrarProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarProveedoresActionPerformed
        RegistrarProveedor RegistrarProveedor = new RegistrarProveedor();
        RegistrarProveedor.setVisible(true);
        this.setVisible(false);
        RegistrarProveedor.setResizable(false);
        RegistrarProveedor.setLocationRelativeTo(null);
    }//GEN-LAST:event_RegistrarProveedoresActionPerformed

    private void jMenuItem14ProveedoressurtenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ProveedoressurtenActionPerformed
        ProveedoresSurtenproducto i = new ProveedoresSurtenproducto();
        i.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem14ProveedoressurtenActionPerformed

    private void jMenuItemRegistrarVendedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegistrarVendedoresActionPerformed
        RegistroVendedor R = new RegistroVendedor();
        R.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItemRegistrarVendedoresActionPerformed

    private void jMenuItem15facturaaclientesvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15facturaaclientesvActionPerformed
        ConsultarVendedores c = new ConsultarVendedores();
        c.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem15facturaaclientesvActionPerformed

    private void jMenuItem12RegistrarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12RegistrarProductosActionPerformed
        RegistrarProductos Productos = new RegistrarProductos();
        Productos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem12RegistrarProductosActionPerformed

    private void RegistrarProveedores1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarProveedores1ActionPerformed
        RegistrarFactura r = new RegistrarFactura();
        this.setVisible(false);
        r.setVisible(true);
        r.setLocationRelativeTo(null);
    }//GEN-LAST:event_RegistrarProveedores1ActionPerformed

    private void jMenuItemconsultaracturaporfechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemconsultaracturaporfechaActionPerformed
        ConsultarFacturasRangoFechas f = new ConsultarFacturasRangoFechas();
        this.setVisible(false);
        f.setVisible(true);

    }//GEN-LAST:event_jMenuItemconsultaracturaporfechaActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        
        ConsultarFacCanceladas c = new ConsultarFacCanceladas();
        this.setVisible(false);
        c.setVisible(true);
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        ConsultarSaldosCliente c = new ConsultarSaldosCliente();
        this.setVisible(false);
        c.setVisible(true);
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenuItem1stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1stockActionPerformed
        StockInventario s = new StockInventario();
        s.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem1stockActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem RegistrarProveedores;
    private javax.swing.JMenuItem RegistrarProveedores1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12RegistrarProductos;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14Proveedoressurten;
    private javax.swing.JMenuItem jMenuItem15facturaaclientesv;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem1stock;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItemRegistrarVendedores;
    private javax.swing.JMenuItem jMenuItemRegistrarcliente;
    private javax.swing.JMenuItem jMenuItemconsultaracturaporfecha;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
