/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Entidades.Entidad_Cliente;
import Entidades.Entidad_DetalleFactura;
import Entidades.Entidad_Facturav;
import ImplementacionDao.ConsultarFacturas_Implement;
import ImplementacionDao.Facturas_Clientes_Implements;
import PatronDao.Facturas_ClientesDao;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author marti
 */
public class Mostrar_Facturas extends javax.swing.JFrame {

    /**
     * Creates new form Mostrar_Facturas
     */
    DefaultTableModel modelo = new DefaultTableModel();

    public Mostrar_Facturas() {
        initComponents();
        this.setTitle("Mostrar Facturas");
        ExtraerclienteJcomboxx();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        deshabilitar();
        this.setSize(new Dimension(806, 580));
        // this.jTable1.setModel(modelo);

//        this.setMinimumSize(new Dimension(200, 200));
    }

//    public void ExtraerFacturav() {
//        int idcliente = Integer.parseInt(this.jComboBox1idcliente.getSelectedItem().toString());
//        Facturas_ClientesDao d = new Facturas_Clientes_Implements();
//        Entidad_Facturav h = new Entidad_Facturav(idcliente);
//        d.ExtraerFactura(h);
//        this.jTextFieldcodigofactura.setText(String.valueOf(h.getIdfactura()));
//        this.jTextFieldfromadepago.setText(h.getFormapago());
//        this.jDateChooser1fecha.setDate(h.getFecha());
//    }
    public void ExtraerclienteJcomboxx() {
        Facturas_ClientesDao d = new Facturas_Clientes_Implements();
        d.jcommboxClientes(jComboBox1idcliente);
    }

    public void ExtraerNombreCliente() {
        int idcliente = Integer.parseInt(this.jComboBox1idcliente.getSelectedItem().toString());
        Facturas_ClientesDao d = new Facturas_Clientes_Implements();
        Entidad_Cliente h = new Entidad_Cliente(idcliente);
        d.ExtraerNombreCLiente(h);
        this.jTextFieldnombre.setText(h.getNombreCliente());
    }

//    public void agregar() {
//        modelo.addColumn("N°Factura");
//        modelo.addColumn("N° Producto");
//        modelo.addColumn("Descripcion");
//        modelo.addColumn("Cantidad");
//        modelo.addColumn("Precio");
//
//    }
    public void mostraTablaMsql() {

        int idcliente = Integer.parseInt(this.jComboBox1idcliente.getSelectedItem().toString());
        int idfacturav = Integer.parseInt(this.jTextFieldcodigofacturav.getText());
        Facturas_ClientesDao d = new Facturas_Clientes_Implements();
        Entidad_Facturav p = new Entidad_Facturav(idcliente, idfacturav);
        Entidad_DetalleFactura fv = new Entidad_DetalleFactura(idfacturav);
        d.ExtraerTabla(jTable1, p, fv);

    }

    public void deshabilitar() {
        this.jTextFieldnombre.setEditable(false);
        this.jTextFieldcodigofacturav.setEditable(false);
        this.jDateChooser1fecha.setEnabled(false);
        this.jTable1.setEnabled(false);
        this.jTextFieldfromadepago.setEditable(false);
    }

//    public void ExtraerClienteJtexfiel() {
//        int id_cliente = Integer.parseInt(this.jComboBox1idcliente.getSelectedItem().toString());
//        ConsultarFacturas_Implement consultar = new ConsultarFacturas_Implement();
//        Entidad_Cliente entidad = new Entidad_Cliente(id_cliente);
//        consultar.ExtraerCLienteBD(entidad);
//        this.jTextField1NombreCliente.setText(entidad.getNombreCliente());
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1Consultar = new javax.swing.JButton();
        jButton2Limpiar = new javax.swing.JButton();
        jComboBox1idcliente = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldcodigofacturav = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jDateChooser1fecha = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldfromadepago = new javax.swing.JTextField();
        jTextFieldnombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Id  Cliente:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "N°Factura", "N°Producto", "Descripcion", "Cantidad", "Subtotal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1Consultar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1Consultar.setText("CONSULTAR");
        jButton1Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ConsultarActionPerformed(evt);
            }
        });

        jButton2Limpiar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2Limpiar.setText("LIMPIAR");
        jButton2Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2LimpiarActionPerformed(evt);
            }
        });

        jComboBox1idcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1idclienteActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Codigo Factura:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Nombre Cliente:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("fecha:");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Forma de pago:");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("DETALLES  FACTURA");

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setText("SALIR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1Consultar)
                        .addGap(57, 57, 57)
                        .addComponent(jButton2Limpiar)
                        .addGap(82, 82, 82)
                        .addComponent(jButton3)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 713, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox1idcliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldcodigofacturav, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(22, 22, 22)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jDateChooser1fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(130, 130, 130)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(279, 279, 279))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldfromadepago, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(261, 261, 261)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel1)
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox1idcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldcodigofacturav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDateChooser1fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldfromadepago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1Consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2Limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2LimpiarActionPerformed
        Facturas_ClientesDao d = new Facturas_Clientes_Implements();
        d.EliminarTabla(jTable1);
//        int i = 0;
//
//      JOptionPane.showMessageDialog(null, "tabla" + this.jTable1.getColumnCount() + "modelo " + modelo.getColumnCount());
//        for (int j = 0; j < modelo.getRowCount(); j++) {
//           this.jTable1.remove(j);
//        }

        this.jTextFieldcodigofacturav.setText("");
        this.jTextFieldnombre.setText("");
        this.jComboBox1idcliente.setSelectedItem(0);
        this.jTextFieldfromadepago.setText("");
        this.jDateChooser1fecha.setDate(null);
        this.jButton1Consultar.setEnabled(true);
    }//GEN-LAST:event_jButton2LimpiarActionPerformed

    private void jButton1ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ConsultarActionPerformed
        if (this.jComboBox1idcliente.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Por favor Ingrese el numero de cedula del cliente  a consultar");
        } else {
            int idcliente = Integer.parseInt(this.jComboBox1idcliente.getSelectedItem().toString());
            Facturas_ClientesDao d = new Facturas_Clientes_Implements();
            Entidad_Facturav h = new Entidad_Facturav(idcliente);
            d.ExtraerFactura(h);
            this.jTextFieldcodigofacturav.setText(String.valueOf(h.getIdfactura()));
            this.jTextFieldfromadepago.setText(h.getFormapago());
            this.jDateChooser1fecha.setDate(h.getFecha());

            mostraTablaMsql();
            this.jButton1Consultar.setEnabled(false);

        }
    }//GEN-LAST:event_jButton1ConsultarActionPerformed

    private void jComboBox1idclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1idclienteActionPerformed

        ExtraerNombreCliente();

    }//GEN-LAST:event_jComboBox1idclienteActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        Inicio i = new Inicio();
        i.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mostrar_Facturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mostrar_Facturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mostrar_Facturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mostrar_Facturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mostrar_Facturas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Consultar;
    private javax.swing.JButton jButton2Limpiar;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1idcliente;
    private com.toedter.calendar.JDateChooser jDateChooser1fecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldcodigofacturav;
    private javax.swing.JTextField jTextFieldfromadepago;
    private javax.swing.JTextField jTextFieldnombre;
    // End of variables declaration//GEN-END:variables
}
