/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Entidades.Entidad_EntradaProductos;
import Entidades.Entidad_Producto;
import ImplementacionDao.Consultarproveedoressurtenproducto_Implement;
import PatronDao.ConsultarproveedoressurtenproductoDao;
import PatronDao.ProveedorDao;

/**
 *
 * @author marti
 */
public class ProveedoresSurtenproducto extends javax.swing.JFrame {

    /**
     * Creates new form ProveedoresSurtenproducto
     */
    ConsultarproveedoressurtenproductoDao d = new Consultarproveedoressurtenproducto_Implement();

    public ProveedoresSurtenproducto() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
//        this.jComboBox1idProducto.addItem(String.valueOf(0));
        this.setTitle("Proveedores que surten producto");
        this.jTable1.setEnabled(false);
//        this.jTextField2ddescripcion.setEditable(false);
//        d.jcommboxPruducto(jComboBox1idProducto);
    }

//    public void Exttraernombre() {
//        int idproducto = Integer.parseInt(this.jComboBox1idProducto.getSelectedItem().toString());
//        ConsultarproveedoressurtenproductoDao d = new Consultarproveedoressurtenproducto_Implement();
//        Entidad_Producto p = new Entidad_Producto(idproducto);
//        d.ExtraerProductoBD(p);
//        this.jTextField2ddescripcion.setText(String.valueOf(p.getDescripcion()));
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1limpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2salir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton3Consultar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1limpiar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1limpiar.setText("LIMPIAR");
        jButton1limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1limpiarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "N°Producto", "N° Proveedor", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton2salir.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2salir.setText("SALIR");
        jButton2salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2salirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("CONSULTAR PROVEEDOR!");

        jButton3Consultar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3Consultar.setText("CONSULTAR");
        jButton3Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3Consultar)
                        .addGap(43, 43, 43)
                        .addComponent(jButton1limpiar)
                        .addGap(34, 34, 34)
                        .addComponent(jButton2salir))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2salir, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3Consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2salirActionPerformed
        // TODO add your handling code here:
        Inicio i = new Inicio();
        i.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jButton2salirActionPerformed

    private void jButton1limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1limpiarActionPerformed

        ConsultarproveedoressurtenproductoDao d = new Consultarproveedoressurtenproducto_Implement();
        d.EliminarTabla(jTable1);
        this.jButton1limpiar.setEnabled(false);
        this.jButton3Consultar.setEnabled(true);
//        this.jComboBox1idProducto.setSelectedIndex(1);
//        this.jTextField2ddescripcion.setText("");
    }//GEN-LAST:event_jButton1limpiarActionPerformed

    private void jButton3ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ConsultarActionPerformed

       // int idproducto = Integer.parseInt(this.jComboBox1idProducto.getSelectedItem().toString());
        ConsultarproveedoressurtenproductoDao d = new Consultarproveedoressurtenproducto_Implement();
         Entidad_EntradaProductos  p = new  Entidad_EntradaProductos ();
        d.Mostrar(jTable1, p);
        this.jButton3Consultar.setEnabled(false);
    }//GEN-LAST:event_jButton3ConsultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProveedoresSurtenproducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProveedoresSurtenproducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProveedoresSurtenproducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProveedoresSurtenproducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProveedoresSurtenproducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1limpiar;
    private javax.swing.JButton jButton2salir;
    private javax.swing.JButton jButton3Consultar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
