/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Entidades.Entidad_Cliente;
import ImplementacionDao.Clienteimplement;
import PatronDao.ClientesDao;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author marti
 */
public class RegistrarClientes extends javax.swing.JFrame {

    DefaultTableModel modelo = new DefaultTableModel();

    public void limpiar() {

        this.jTextFieldNumcedula.setText("");
        this.jTextFieldnombre.setText("");
        this.jTextFieldedad.setText("");
        this.jTextFieldsexo.setText("");
        this.jTextFieldtelefono.setText("");
        this.jTextFieldcorreo.setText("");
       
        this.jTextFielddireccion.setText("");

    }

    /**
     * Creates new form RegistrarClientes
     */
    public RegistrarClientes() {
        initComponents();
        String titulo[] = new String[]{"N°Cedula", "Nombre", "Edad", "Direccion", "sexo", "Telefono", "CorreoElectronico", "Saldo"};
        modelo.setColumnIdentifiers(titulo);
        //modelo.setColumnIdentifiers(titulo);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        Mostrar();
        this.setTitle("Registro de Clientes");
    }

    public void agregar() {
        
        modelo.addRow(new Object[]{
            this.jTextFieldNumcedula.getText(), this.jTextFieldnombre.getText(), this.jTextFieldedad.getText(), this.jTextFielddireccion.getText(), this.jTextFieldsexo.getText(), this.jTextFieldtelefono.getText(), this.jTextFieldcorreo.getText()});
        this.jTabletabla.setModel(modelo);
    }

    public void Mostrar() {
        Clienteimplement cliente = new Clienteimplement();
        cliente.MostrarClienteDao(this.jTabletabla);
        //JOptionPane.showMessageDialog(null, " entro a mostrar");
        // JOptionPane.showMessageDialog(null, " entro a mostrar en jframe");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFielddireccion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldNumcedula = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldnombre = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldsexo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldtelefono = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldcorreo = new javax.swing.JTextField();
        jTextFieldedad = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabletabla = new javax.swing.JTable();
        Registrar = new javax.swing.JButton();
        jButton2eliminar = new javax.swing.JButton();
        jButtonmodificar = new javax.swing.JButton();
        jButtonsalir = new javax.swing.JButton();
        jButton1Buscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("REGISTRO DE CLIENTES");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Correo electronico:");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("N° Cedula:");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setText("Nombre:");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setText("Edad:");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setText("Sexo:");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setText("Telefono:");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel13.setText("Direccion:");

        jTabletabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N°Cedula", "Nombre", "Edad", "Direccion", "Sexo", "Telefono", "CorreoElectronico"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTabletabla);

        Registrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Registrar 72 px.png"))); // NOI18N
        Registrar.setBorder(null);
        Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarActionPerformed(evt);
            }
        });

        jButton2eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Eliminar 72px.png"))); // NOI18N
        jButton2eliminar.setBorder(null);
        jButton2eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2eliminarActionPerformed(evt);
            }
        });

        jButtonmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Modificar 72 px.png"))); // NOI18N
        jButtonmodificar.setBorder(null);
        jButtonmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonmodificarActionPerformed(evt);
            }
        });

        jButtonsalir.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonsalir.setText("SALIR");
        jButtonsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsalirActionPerformed(evt);
            }
        });

        jButton1Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar72px.png"))); // NOI18N
        jButton1Buscar.setBorder(null);
        jButton1Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1BuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 793, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldtelefono)
                                    .addComponent(jTextFieldNumcedula, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel12))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jTextFieldnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(38, 38, 38)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(jTextFieldedad, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(61, 61, 61)
                                                .addComponent(jTextFielddireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(71, 71, 71)
                                                .addComponent(jLabel13)))
                                        .addGap(57, 57, 57)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldsexo, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(jTextFieldcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(Registrar)
                        .addGap(27, 27, 27)
                        .addComponent(jButton2eliminar)
                        .addGap(58, 58, 58)
                        .addComponent(jButtonmodificar)
                        .addGap(44, 44, 44)
                        .addComponent(jButton1Buscar)
                        .addGap(55, 55, 55)
                        .addComponent(jButtonsalir)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFielddireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNumcedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldsexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldtelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2eliminar)
                    .addComponent(jButtonmodificar)
                    .addComponent(Registrar)
                    .addComponent(jButton1Buscar)
                    .addComponent(jButtonsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsalirActionPerformed
        // TODO add your handling code here:
        Inicio i = new Inicio();
        i.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonsalirActionPerformed

    private void RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarActionPerformed

        if (this.jTextFieldsexo.getText().equals("") || this.jTextFieldNumcedula.getText().equals("") || this.jTextFieldnombre.getText().equals("") || this.jTextFieldedad.getText().equals("")
                || this.jTextFielddireccion.getText().equals("") || this.jTextFieldsexo.getText().equals("")
                || this.jTextFieldtelefono.getText().equals("") || this.jTextFieldcorreo.getText().equals("")
                 ) {
            JOptionPane.showMessageDialog(null, " Por favor ingresar los datos de todos los campos ");
        } else {
            int cedula = Integer.parseInt(this.jTextFieldNumcedula.getText());
            String nombre = this.jTextFieldnombre.getText();
            int edad = Integer.parseInt(this.jTextFieldedad.getText());
            String direccion = this.jTextFielddireccion.getText();
            String sexo = this.jTextFieldsexo.getText();
            String telefono = this.jTextFieldtelefono.getText();
            
            String correo = this.jTextFieldcorreo.getText();
            JOptionPane.showMessageDialog(null, "El Cliente se registro correctamente ");
            ClientesDao clientedao = new Clienteimplement();
            Entidad_Cliente entidadcliente = new Entidad_Cliente(cedula, nombre, edad, direccion, sexo, correo, telefono);
            clientedao.Insertar(entidadcliente);
            agregar();
            limpiar();
        }

    }//GEN-LAST:event_RegistrarActionPerformed

    private void jButton1BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1BuscarActionPerformed
        ClientesDao clientedao = new Clienteimplement();
        if (this.jTextFieldNumcedula.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor Ingrese la cedula del usuario a buscar ");
        } else {
            int id_cliente = Integer.parseInt(this.jTextFieldNumcedula.getText());
            Entidad_Cliente entidadcliente = new Entidad_Cliente(id_cliente);
            clientedao.buscar(entidadcliente);
            this.jTextFieldNumcedula.setText(String.valueOf(entidadcliente.getNumCedula()));
            this.jTextFieldnombre.setText(entidadcliente.getNombreCliente());
            this.jTextFieldedad.setText(String.valueOf(entidadcliente.getEdad()));
            this.jTextFielddireccion.setText(entidadcliente.getDireccion());
            this.jTextFieldsexo.setText(entidadcliente.getSexo());
            this.jTextFieldtelefono.setText(entidadcliente.getTelefono());
            this.jTextFieldcorreo.setText(entidadcliente.getCorreoElectronico());
            JOptionPane.showMessageDialog(null, " Registro encontrado ");
        }
        limpiar();
    }//GEN-LAST:event_jButton1BuscarActionPerformed

    private void jButton2eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2eliminarActionPerformed
        ClientesDao clientedao = new Clienteimplement();
        if (this.jTextFieldNumcedula.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor Ingrese la cedula del usuario a eliminar ");
        } else {
            int id = Integer.parseInt(this.jTextFieldNumcedula.getText());
            Entidad_Cliente entidadcliente = new Entidad_Cliente(id);
            clientedao.Eliminar(entidadcliente);
            JOptionPane.showMessageDialog(null, "EL registro se elimino satisfactoriamente de la base de datos ");
            limpiar();
        }
    }//GEN-LAST:event_jButton2eliminarActionPerformed

    private void jButtonmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonmodificarActionPerformed

        if (this.jTextFieldsexo.getText().equals("") || this.jTextFieldNumcedula.getText().equals("") || this.jTextFieldnombre.getText().equals("") || this.jTextFieldedad.getText().equals("")
                || this.jTextFielddireccion.getText().equals("") || this.jTextFieldsexo.getText().equals("")
                || this.jTextFieldtelefono.getText().equals("") || this.jTextFieldcorreo.getText().equals("")
               ) {
            JOptionPane.showMessageDialog(null, " Por favor ingresar los datos de todos los campos ");
        } else {
            int cedula = Integer.parseInt(this.jTextFieldNumcedula.getText());
            String nombre = this.jTextFieldnombre.getText();
            int edad = Integer.parseInt(this.jTextFieldedad.getText());
            String direccion = this.jTextFielddireccion.getText();
            String sexo = this.jTextFieldsexo.getText();
            String telefono = this.jTextFieldtelefono.getText();
           
            String correo = this.jTextFieldcorreo.getText();
            Entidad_Cliente entidadcliente = new Entidad_Cliente(cedula, nombre, edad, direccion, sexo, correo, telefono);
            Clienteimplement modificar = new Clienteimplement();
            modificar.modificar(entidadcliente);
            JOptionPane.showMessageDialog(null, " Registro modificado con exito");
        }
        limpiar();
    }//GEN-LAST:event_jButtonmodificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Registrar;
    private javax.swing.JButton jButton1Buscar;
    private javax.swing.JButton jButton2eliminar;
    private javax.swing.JButton jButtonmodificar;
    private javax.swing.JButton jButtonsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabletabla;
    private javax.swing.JTextField jTextFieldNumcedula;
    private javax.swing.JTextField jTextFieldcorreo;
    private javax.swing.JTextField jTextFielddireccion;
    private javax.swing.JTextField jTextFieldedad;
    private javax.swing.JTextField jTextFieldnombre;
    private javax.swing.JTextField jTextFieldsexo;
    private javax.swing.JTextField jTextFieldtelefono;
    // End of variables declaration//GEN-END:variables
}
