/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Entidades.*;
import ImplementacionDao.*;
import PatronDao.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author marti
 */
public class RegistrarProductos extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarProductos
     */
    DefaultTableModel modelo = new DefaultTableModel();

    public void limpiar() {
        this.jTextFieldNumProducto.setText("");
        this.jTextField7Descripcion.setText("");
        this.jTextField5Categoria.setText("");
        this.jTextField8Precio.setText("");
        this.jTextField8existencias.setText("");
    }

    public RegistrarProductos() {
        initComponents();
        String titulo[] = new String[]{"N° Producto", "Descripcion Producto", "Categoria", "Precio Unitario", "Existencias Inciales"};
        modelo.setColumnIdentifiers(titulo);
        //modelo.setColumnIdentifiers(titulo);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("Registro de Producto");
        Mostrar();
        this.jTabletabla.setEnabled(false);
    }

    public void agregar() {
        modelo.addRow(new Object[]{
            this.jTextFieldNumProducto.getText(), this.jTextField7Descripcion.getText(), this.jTextField5Categoria.getText(),
            this.jTextField8Precio.getText(), this.jTextField8existencias.getText()});
        this.jTabletabla.setModel(modelo);
    }

    public void Mostrar() {
        Producto_Implement Producto = new Producto_Implement();
        Producto.MostrarProductoDao(this.jTabletabla);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldNumProducto = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField7Descripcion = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField5Categoria = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabletabla = new javax.swing.JTable();
        jButton1Eliminar = new javax.swing.JButton();
        jButton2Modificar = new javax.swing.JButton();
        jButton3Registrar = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1Buscar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jTextField8existencias = new javax.swing.JTextField();
        jTextField8Precio = new javax.swing.JTextField();

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel13.setText("Direccion:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("REGISTRO DE PRODUCTOS");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("N° Producto:");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setText("Descripcion:");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel14.setText("Categoria:");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setText("Precio:");

        jTabletabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N° Producto", "Descripcion", "Categoria", "Precio unidad", "Existencias Iniciales"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTabletabla.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(jTabletabla);

        jButton1Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Eliminar 72px.png"))); // NOI18N
        jButton1Eliminar.setBorder(null);
        jButton1Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1EliminarActionPerformed(evt);
            }
        });

        jButton2Modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Modificar 72 px.png"))); // NOI18N
        jButton2Modificar.setBorder(null);
        jButton2Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ModificarActionPerformed(evt);
            }
        });

        jButton3Registrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Registrar 72 px.png"))); // NOI18N
        jButton3Registrar.setBorder(null);
        jButton3Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3RegistrarActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton4.setText("SALIR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton1Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar72px.png"))); // NOI18N
        jButton1Buscar.setBorder(null);
        jButton1Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1BuscarActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setText("Existencias Inciales:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jButton3Registrar)
                        .addGap(36, 36, 36)
                        .addComponent(jButton2Modificar)
                        .addGap(50, 50, 50)
                        .addComponent(jButton1Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jButton1Buscar)
                        .addGap(49, 49, 49)
                        .addComponent(jButton4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel8)
                                    .addComponent(jTextFieldNumProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField8existencias))
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField7Descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField5Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jTextField8Precio, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel14)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNumProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7Descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField8Precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField8existencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton3Registrar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1Buscar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1Eliminar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2Modificar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Inicio i = new Inicio();
        i.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1BuscarActionPerformed
        ProductoDao p = new Producto_Implement();
        if (this.jTextFieldNumProducto.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor Ingrese el codigo del producto a buscar ");
        } else {
            int idvendedor = Integer.parseInt(this.jTextFieldNumProducto.getText());
            Entidad_Producto entidadp = new Entidad_Producto(idvendedor);
            p.buscar(entidadp);
            this.jTextFieldNumProducto.setText(String.valueOf(entidadp.getIdProducto()));
            this.jTextField7Descripcion.setText(entidadp.getDescripcion());
            this.jTextField5Categoria.setText(entidadp.getCategoria());
            this.jTextField8Precio.setText(String.valueOf(entidadp.getPrecio()));
            this.jTextField8existencias.setText(String.valueOf(entidadp.getExistencias_iniciales()));
            if (this.jTextField5Categoria.getText().equals("")) {

            } else {

                JOptionPane.showMessageDialog(null, " Registro encontrado ");
            }
        }
        limpiar();
    }//GEN-LAST:event_jButton1BuscarActionPerformed

    private void jButton3RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3RegistrarActionPerformed

        if (this.jTextFieldNumProducto.getText().equals("") || this.jTextField7Descripcion.getText().equals("") || this.jTextField5Categoria.getText().equals("")
                || this.jTextField8Precio.getText().equals("") || this.jTextField8existencias.getText().equals("")) {
            JOptionPane.showMessageDialog(null, " Por favor ingresar los datos de todos los campos ");
        } else {
            boolean f = false, p = false;
            if (this.jTabletabla.getRowCount() == 0) {

                int idProducto = Integer.parseInt(this.jTextFieldNumProducto.getText());
                String descripcion = this.jTextField7Descripcion.getText();
                String categoria = this.jTextField5Categoria.getText();
                int precio = Integer.parseInt(this.jTextField8Precio.getText());
                int existencias = Integer.parseInt(this.jTextField8existencias.getText());
                JOptionPane.showMessageDialog(null, "El Producto se registro Exitosamente ");
                ProductoDao ProductoDao = new Producto_Implement();
                Entidad_Producto entidadVendedor = new Entidad_Producto(idProducto, descripcion, categoria, precio, existencias);
                ProductoDao.Insertar(entidadVendedor);
                agregar();
                limpiar();
            } else {

                for (int i = 0; i < this.jTabletabla.getRowCount(); i++) { // recorro la tabla para verificar que el producto a ingresa no sea el mismo 
                    if (jTabletabla.getValueAt(i, 1).equals(this.jTextField7Descripcion.getText())) { // verifico el producto al igual que ya esta registrado 1 que es la colunna del producto
                        f = true;
                    }

                    if (jTabletabla.getValueAt(i, 0).equals(this.jTextFieldNumProducto.getText())) { // verifico el producto al igual que ya esta registrado 1 que es la colunna del producto
                        p = true;
                    }

                }

                if (f == true || p == true) {
                    JOptionPane.showMessageDialog(null, "el Producto y/o Codigo ya esta registrado ");
                    limpiar();
                } else {

                    int idProducto = Integer.parseInt(this.jTextFieldNumProducto.getText());
                    String descripcion = this.jTextField7Descripcion.getText();
                    String categoria = this.jTextField5Categoria.getText();
                    int precio = Integer.parseInt(this.jTextField8Precio.getText());
                    int existencias = Integer.parseInt(this.jTextField8existencias.getText());
                    JOptionPane.showMessageDialog(null, "El Producto se registro Exitosamente ");
                    ProductoDao ProductoDao = new Producto_Implement();
                    Entidad_Producto entidadVendedor = new Entidad_Producto(idProducto, descripcion, categoria, precio, existencias);
                    ProductoDao.Insertar(entidadVendedor);
                    agregar();
                    limpiar();
                }
            }
        }
    }//GEN-LAST:event_jButton3RegistrarActionPerformed

    private void jButton1EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1EliminarActionPerformed
        ProductoDao ProductoDao = new Producto_Implement();
        if (this.jTextFieldNumProducto.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor Ingrese el codigo  del producto a eliminar ");
        } else {
            int idProducto = Integer.parseInt(this.jTextFieldNumProducto.getText());
            Entidad_Producto Entidad_Producto = new Entidad_Producto(idProducto);
            ProductoDao.Eliminar(Entidad_Producto);
            JOptionPane.showMessageDialog(null, "EL registro se elimino satisfactoriamente de la base de datos ");
            limpiar();
        }
    }//GEN-LAST:event_jButton1EliminarActionPerformed

    private void jButton2ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ModificarActionPerformed

        if (this.jTextFieldNumProducto.getText().equals("") || this.jTextField7Descripcion.getText().equals("") || this.jTextField5Categoria.getText().equals("") || this.jTextField8Precio.getText().equals("")) {
            JOptionPane.showMessageDialog(null, " Por favor ingresar los datos de todos los campos ");
        } else {
            int idProducto = Integer.parseInt(this.jTextFieldNumProducto.getText());
            String descripcion = this.jTextField7Descripcion.getText();
            String categoria = this.jTextField5Categoria.getText();
            int precio = Integer.parseInt(this.jTextField8Precio.getText());
            int existencias = Integer.parseInt(this.jTextField8existencias.getText());
            JOptionPane.showMessageDialog(null, "El Producto se registro Exitosamente ");
            ProductoDao ProductoDao = new Producto_Implement();
            Entidad_Producto entidadVendedor = new Entidad_Producto(idProducto, descripcion, categoria, precio, existencias);
            ProductoDao.modificar(entidadVendedor);
            JOptionPane.showMessageDialog(null, " Registro modificado con exito");
        }
        limpiar();
    }//GEN-LAST:event_jButton2ModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarProductos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarProductos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarProductos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarProductos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Buscar;
    private javax.swing.JButton jButton1Eliminar;
    private javax.swing.JButton jButton2Modificar;
    private javax.swing.JButton jButton3Registrar;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabletabla;
    private javax.swing.JTextField jTextField5Categoria;
    private javax.swing.JTextField jTextField7Descripcion;
    private javax.swing.JTextField jTextField8Precio;
    private javax.swing.JTextField jTextField8existencias;
    private javax.swing.JTextField jTextFieldNumProducto;
    // End of variables declaration//GEN-END:variables
}
