/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Entidades.Entidad_Cliente;
import Entidades.Entidad_Proveedor;
import ImplementacionDao.Clienteimplement;
import ImplementacionDao.Proveedorimplement;
import PatronDao.ProveedorDao;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author marti
 */
public class RegistrarProveedor extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarProveedor
     */
    DefaultTableModel modelo = new DefaultTableModel();

    public RegistrarProveedor() {
        initComponents();
        String titulo[] = new String[]{"N°Proveedor ", "Nombre", "Pagina Web", "Direccion", "Telefono", "CorreoElectronico"};
        modelo.setColumnIdentifiers(titulo);
        //modelo.setColumnIdentifiers(titulo);
        Mostrar();
        this.setTitle("Registro de Proveedores");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.jTabletabla.setEnabled(false);
    }

    public void limpiar() {

        this.jtexfieldnumproveedor.setText("");
        this.jTextFieldpaginaweb.setText("");
        this.jTextFieldtelefono.setText("");
        this.jTextFieldcorreo.setText("");
        this.jTextFielddireccion.setText("");
        this.JtexFieldnombre.setText("");

    }

    public void Mostrar() {
        Proveedorimplement MostrarProveedores = new Proveedorimplement();
        MostrarProveedores.MostrarProveedorDao(jTabletabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFielddireccion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtexfieldnumproveedor = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        JtexFieldnombre = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldtelefono = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldcorreo = new javax.swing.JTextField();
        jTextFieldpaginaweb = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabletabla = new javax.swing.JTable();
        Registrar = new javax.swing.JButton();
        jButton2eliminar = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1Buscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("REGISTRO DE PROVEEDORES");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Correo electronico:");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("N° Proveedor:");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setText("Nombre:");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setText("Pagina web:");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setText("Telefono:");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel13.setText("Direccion:");

        jTabletabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N°Proveedor", "Nombre", "Pagina Web", "Direccion", "Telefono", "CorreoElectronico"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTabletabla);

        Registrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Registrar 72 px.png"))); // NOI18N
        Registrar.setBorder(null);
        Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarActionPerformed(evt);
            }
        });

        jButton2eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Eliminar 72px.png"))); // NOI18N
        jButton2eliminar.setBorder(null);
        jButton2eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2eliminarActionPerformed(evt);
            }
        });

        jButtonModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Modificar 72 px.png"))); // NOI18N
        jButtonModificar.setBorder(null);
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton4.setText("SALIR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton1Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar72px.png"))); // NOI18N
        jButton1Buscar.setBorder(null);
        jButton1Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1BuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldtelefono)
                    .addComponent(jtexfieldnumproveedor, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel12))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jTextFieldcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JtexFieldnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldpaginaweb, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFielddireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(Registrar)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2eliminar)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonModificar)
                                .addGap(28, 28, 28)
                                .addComponent(jButton1Buscar)
                                .addGap(31, 31, 31)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jLabel1)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFielddireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtexfieldnumproveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JtexFieldnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldpaginaweb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldtelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Registrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1Buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void agregar() {
        modelo.addRow(new Object[]{
            this.jtexfieldnumproveedor.getText(), this.JtexFieldnombre.getText(), this.jTextFieldpaginaweb.getText(),
            this.jTextFieldtelefono.getText(), this.jTextFielddireccion.getText(), this.jTextFieldcorreo.getText()});
        this.jTabletabla.setModel(modelo);
    }
    private void RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarActionPerformed

        if (this.jtexfieldnumproveedor.getText().equals("") || this.JtexFieldnombre.getText().equals("") || this.jTextFieldpaginaweb.getText().equals("")
                || this.jTextFielddireccion.getText().equals("") || this.jTextFieldtelefono.getText().equals("")) {
            JOptionPane.showMessageDialog(null, " Por favor ingresar los datos de todos los campos ");
        } else {
            //si la tabla esta vacia , osea es el primer elemento a ingresar
            if (this.jTabletabla.getRowCount() == 0) {
                int id_proveedor = Integer.parseInt(this.jtexfieldnumproveedor.getText());
                String nombre = this.JtexFieldnombre.getText();
                String paginaweb = this.jTextFieldpaginaweb.getText();
                String telefono = this.jTextFieldtelefono.getText();
                String direccion = this.jTextFielddireccion.getText();
                String correo = this.jTextFieldcorreo.getText();
                JOptionPane.showMessageDialog(null, "El Proveedor" + nombre + " con codigo " + id_proveedor + " se registro correctamente ");
                ProveedorDao ProveedorDao = new Proveedorimplement();
                Entidad_Proveedor EntidadProveedor = new Entidad_Proveedor(id_proveedor, nombre, paginaweb, telefono, direccion, correo);
                ProveedorDao.Insertar(EntidadProveedor);
                agregar();
                limpiar();
            } else {

                boolean n = false, p = false;
                for (int i = 0; i < this.jTabletabla.getRowCount(); i++) { // recorro la tabla para verificar que el producto a ingresa no sea el mismo 

                    if (jTabletabla.getValueAt(i, 0).toString().equals(this.jtexfieldnumproveedor.getText())) { // verifico el producto al igual que ya esta registrado 1 que es la colunna del producto
                        p = true;
                    }

                    if (jTabletabla.getValueAt(i, 1).equals(this.JtexFieldnombre.getText())) {
                        n = true;

                    }

                }
                if (n == true || p == true) {
                    JOptionPane.showMessageDialog(null, " El Codigo y/o Proveedor ya esta registrado  ");
                } else {

                    int id_proveedor = Integer.parseInt(this.jtexfieldnumproveedor.getText());
                    String nombre = this.JtexFieldnombre.getText();
                    String paginaweb = this.jTextFieldpaginaweb.getText();
                    String telefono = this.jTextFieldtelefono.getText();
                    String direccion = this.jTextFielddireccion.getText();
                    String correo = this.jTextFieldcorreo.getText();
                    JOptionPane.showMessageDialog(null, "El Proveedor" + nombre + " con codigo " + id_proveedor + " se registro correctamente ");
                    ProveedorDao ProveedorDao = new Proveedorimplement();
                    Entidad_Proveedor EntidadProveedor = new Entidad_Proveedor(id_proveedor, nombre, paginaweb, telefono, direccion, correo);
                    ProveedorDao.Insertar(EntidadProveedor);
                    agregar();
                    limpiar();
                }
            }
        }
    }//GEN-LAST:event_RegistrarActionPerformed

    private void jButton2eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2eliminarActionPerformed
        ProveedorDao Proveedordao = new Proveedorimplement();
        if (this.jtexfieldnumproveedor.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor Ingrese la N° del usuario a eliminar ");
        } else {
            int id = Integer.parseInt(this.jtexfieldnumproveedor.getText());
            Entidad_Proveedor Proveedor = new Entidad_Proveedor(id);
            Proveedordao.Eliminar(Proveedor);
            JOptionPane.showMessageDialog(null, "EL registro se elimino satisfactoriamente de la base de datos ");
            limpiar();
        }
    }//GEN-LAST:event_jButton2eliminarActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Inicio i = new Inicio();
        i.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1BuscarActionPerformed
        ProveedorDao ProveedorDao = new Proveedorimplement();
        if (this.jtexfieldnumproveedor.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor Ingrese el codigo del usuario a buscar ");
        } else {
            int id_proveedor = Integer.parseInt(this.jtexfieldnumproveedor.getText());
            Entidad_Proveedor entidadProveedor = new Entidad_Proveedor(id_proveedor);
            ProveedorDao.buscar(entidadProveedor);
            this.jtexfieldnumproveedor.setText(String.valueOf(entidadProveedor.getIdProveedor()));
            this.JtexFieldnombre.setText(entidadProveedor.getNombreProveedor());
            this.jTextFieldpaginaweb.setText(entidadProveedor.getPaginaweb());
            this.jTextFielddireccion.setText(entidadProveedor.getDireccionProveedor());
            this.jTextFieldtelefono.setText(entidadProveedor.getTelefonoProveedor());
            this.jTextFieldcorreo.setText(entidadProveedor.getCorreoElectronico());
            JOptionPane.showMessageDialog(null, " Registro encontrado ");
        }
        limpiar();
    }//GEN-LAST:event_jButton1BuscarActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed

        if (this.jtexfieldnumproveedor.getText().equals("") || this.JtexFieldnombre.getText().equals("") || this.jTextFieldpaginaweb.getText().equals("") || this.jTextFielddireccion.getText().equals("")
                || this.jTextFieldtelefono.getText().equals("") || this.jTextFieldcorreo.getText().equals("")) {
            JOptionPane.showMessageDialog(null, " Por favor ingresar los datos de todos los campos ");
        } else {
            int id_proveedor = Integer.parseInt(this.jtexfieldnumproveedor.getText());
            String nombre = this.JtexFieldnombre.getText();
            String paginaweb = this.jTextFieldpaginaweb.getText();
            String telefono = this.jTextFieldtelefono.getText();
            String direccion = this.jTextFielddireccion.getText();
            String correo = this.jTextFieldcorreo.getText();
            Entidad_Proveedor EntidadProveedor = new Entidad_Proveedor(id_proveedor, nombre, paginaweb, telefono, direccion, correo);
            ProveedorDao modificar = new Proveedorimplement();
            modificar.modificar(EntidadProveedor);
            JOptionPane.showMessageDialog(null, " Registro modificado con exito");
        }
        limpiar();
    }//GEN-LAST:event_jButtonModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarProveedor.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarProveedor.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarProveedor.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarProveedor.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarProveedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JtexFieldnombre;
    private javax.swing.JButton Registrar;
    private javax.swing.JButton jButton1Buscar;
    private javax.swing.JButton jButton2eliminar;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabletabla;
    private javax.swing.JTextField jTextFieldcorreo;
    private javax.swing.JTextField jTextFielddireccion;
    private javax.swing.JTextField jTextFieldpaginaweb;
    private javax.swing.JTextField jTextFieldtelefono;
    private javax.swing.JTextField jtexfieldnumproveedor;
    // End of variables declaration//GEN-END:variables
}
