/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Entidades.*;
import ImplementacionDao.*;
import PatronDao.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author marti
 */
public class RegistroVendedor extends javax.swing.JFrame {

    /**
     * Creates new form RegistroVendedor
     */
    DefaultTableModel modelo = new DefaultTableModel();

    public void limpiar() {

        this.jTextFieldNumVendedor.setText("");
        this.jTextField7nombre.setText("");
        this.jTextField8telefono.setText("");
    }

    public RegistroVendedor() {
        initComponents();
        this.setTitle("Registro de Vendedores");
        String titulo[] = new String[]{"N°Vendedor", "Nombre Vendedor", "Telefono"};

        modelo.setColumnIdentifiers(titulo);
        this.jTabletabla.setModel(modelo);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.jTabletabla.setEnabled(false);
        Mostrar();
    }

    public void agregar() {
        modelo.addRow(new Object[]{
            this.jTextFieldNumVendedor.getText(), this.jTextField7nombre.getText(), this.jTextField8telefono.getText()});
        this.jTabletabla.setModel(modelo);
    }

    public void Mostrar() {
        Vendedor_Implement Vendedor = new Vendedor_Implement();
        Vendedor.Mostrar(this.jTabletabla);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldNumVendedor = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField7nombre = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField8telefono = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabletabla = new javax.swing.JTable();
        jButton1Registrar = new javax.swing.JButton();
        jButton2Modificar = new javax.swing.JButton();
        jButton3Eliminar = new javax.swing.JButton();
        jButton1Buscar = new javax.swing.JButton();
        jButtonsalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("REGISTRO DE VENDEDORES");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("N° Vendedor:");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setText("Nombre:");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setText("Telefono:");

        jTabletabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N° Vendedor", "Nombre", "Telefono"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTabletabla);

        jButton1Registrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Registrar 72 px.png"))); // NOI18N
        jButton1Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1RegistrarActionPerformed(evt);
            }
        });

        jButton2Modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Modificar 72 px.png"))); // NOI18N
        jButton2Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ModificarActionPerformed(evt);
            }
        });

        jButton3Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Eliminar 72px.png"))); // NOI18N
        jButton3Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3EliminarActionPerformed(evt);
            }
        });

        jButton1Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar72px.png"))); // NOI18N
        jButton1Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1BuscarActionPerformed(evt);
            }
        });

        jButtonsalir.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonsalir.setText("SALIR");
        jButtonsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jButton1Registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jButton2Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(jButton1Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(jButtonsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(86, 86, 86)
                            .addComponent(jLabel1))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(jTextFieldNumVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(43, 43, 43)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addComponent(jTextField7nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(58, 58, 58)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField8telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(14, 14, 14)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldNumVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField7nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField8telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1Registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addComponent(jButtonsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1BuscarActionPerformed
        VendedorDao VendedorDao = new Vendedor_Implement();
        if (this.jTextFieldNumVendedor.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor Ingrese la cedula del usuario a buscar ");
        } else {
            int idvendedor = Integer.parseInt(this.jTextFieldNumVendedor.getText());
            Entidad_Vendedor entidadVendedor = new Entidad_Vendedor(idvendedor);
            VendedorDao.buscar(entidadVendedor);
            this.jTextFieldNumVendedor.setText(String.valueOf(entidadVendedor.getIdvendedor()));
            this.jTextField7nombre.setText(entidadVendedor.getNombrevendedor());
            this.jTextField8telefono.setText(entidadVendedor.getTelefonovendedor());
            JOptionPane.showMessageDialog(null, " Registro encontrado ");
        }
        limpiar();
    }//GEN-LAST:event_jButton1BuscarActionPerformed

    private void jButton1RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1RegistrarActionPerformed

        if (this.jTextFieldNumVendedor.getText().equals("") || this.jTextField7nombre.getText().equals("") || this.jTextField8telefono.equals("")) {
            JOptionPane.showMessageDialog(null, " Por favor ingresar los datos de todos los campos ");
        } else {
             boolean f = false;
            for (int i = 0; i < this.jTabletabla.getRowCount(); i++) { // recorro la tabla para verificar que el producto a ingresa no sea el mismo 
                if (jTabletabla.getValueAt(i, 0).toString().equals(this.jTextFieldNumVendedor.getText())) { // verifico el producto al igual que ya esta registrado 1 que es la colunna del producto
                f = true;
                }
               

            }
            if (f == true) {
                JOptionPane.showMessageDialog(null, "el codigo ya esta registrado");
                limpiar();
            } else {
            int idvendedor = Integer.parseInt(this.jTextFieldNumVendedor.getText());
            String nombrevendedor = this.jTextField7nombre.getText();
            String telefonovendedor = this.jTextField8telefono.getText();
            JOptionPane.showMessageDialog(null, "El Vendedor se registro correctamente ");
            VendedorDao VendedorDao = new Vendedor_Implement();
            Entidad_Vendedor entidadVendedor = new Entidad_Vendedor(idvendedor, nombrevendedor, telefonovendedor);
            VendedorDao.Insertar(entidadVendedor);
            agregar();
            limpiar();
        }
        }
    }//GEN-LAST:event_jButton1RegistrarActionPerformed

    private void jButtonsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsalirActionPerformed
        // TODO add your handling code here:
        Inicio i = new Inicio();
        i.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonsalirActionPerformed

    private void jButton3EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3EliminarActionPerformed
        VendedorDao VendedorDao = new Vendedor_Implement();
        if (this.jTextFieldNumVendedor.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor Ingrese el codigo  del usuario a eliminar ");
        } else {
           

                int idvendedor = Integer.parseInt(this.jTextFieldNumVendedor.getText());
                Entidad_Vendedor entidadcliente = new Entidad_Vendedor(idvendedor);
                VendedorDao.Eliminar(entidadcliente);
                JOptionPane.showMessageDialog(null, "EL registro se elimino satisfactoriamente de la base de datos ");
                limpiar();
           
        }
    }//GEN-LAST:event_jButton3EliminarActionPerformed

    private void jButton2ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ModificarActionPerformed

        if (this.jTextFieldNumVendedor.getText().equals("") || this.jTextField7nombre.getText().equals("") || this.jTextField8telefono.getText().equals("")) {
            JOptionPane.showMessageDialog(null, " Por favor ingresar los datos de todos los campos ");
        } else {
            int idvendedor = Integer.parseInt(this.jTextFieldNumVendedor.getText());
            String nombrevendedor = this.jTextField7nombre.getText();
            String telefonovendedor = this.jTextField8telefono.getText();
            VendedorDao VendedorDao = new Vendedor_Implement();
            Entidad_Vendedor entidadVendedor = new Entidad_Vendedor(idvendedor, nombrevendedor, telefonovendedor);
            VendedorDao.modificar(entidadVendedor);
            JOptionPane.showMessageDialog(null, " Registro modificado con exito");
        }
        limpiar();
    }//GEN-LAST:event_jButton2ModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroVendedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Buscar;
    private javax.swing.JButton jButton1Registrar;
    private javax.swing.JButton jButton2Modificar;
    private javax.swing.JButton jButton3Eliminar;
    private javax.swing.JButton jButtonsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabletabla;
    private javax.swing.JTextField jTextField7nombre;
    private javax.swing.JTextField jTextField8telefono;
    private javax.swing.JTextField jTextFieldNumVendedor;
    // End of variables declaration//GEN-END:variables
}
